---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloudformation template to create resources for News Board project'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: Environment to deploy. Use staging for limited resources and no alerts.
    Type: String
  BucketName:
    Description: S3 bucket name where all reports will be stored.
    Type: String
  KinesisName:
    Description: Reports from different News Reporter applications are put to this stream .
    Type: String

Resources:
  ReportsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      BucketName: !Join [ "-", [ !Ref Environment, !Ref BucketName ] ]
  ReportsKinesis:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Join [ "-", [ !Ref Environment, !Ref KinesisName ] ]
      RetentionPeriodHours: 24
      ShardCount: 2
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis #Default kms key id